version: '3'


services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "MySecr3tPassword@as2"
      POSTGRES_DB: ${DB_NAME}
    container_name: chatdb
    volumes:
      - ./postgres:/var/lib/postgresql/data
      